#!/usr/bin/env node
/**
 * Build-time image optimisation for static export.
 * Auto-discovers JPG/PNG in public/images and generates responsive AVIF/WebP/JPEG variants.
 */
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, "..");
const IMAGES_DIR = path.join(ROOT, "public", "images");
const OPT_DIR = path.join(IMAGES_DIR, "opt");
const SOURCE_DIR = path.join(ROOT, "image-sources");
const MANIFEST_TS = path.join(ROOT, "src", "data", "image-manifest.ts");

const CARD_WIDTHS = [320, 480, 640, 800];
const HERO_WIDTHS = [640, 960, 1280, 1920];
const OG_SIZE = { width: 1200, height: 630 };
const QUALITY = { avif: 62, webp: 78, jpeg: 82 };

const HERO_NAME_PATTERNS =
  /^(hero-home|og-default|compare|cruise-port|photography|highlights|portofino|riviera-coast|hero|old-town|fortress|panorama|aerial|landscape|coastline|marina|cathedral|historic|pilgrimage|santiago|hercules|galicia|roque|kotor-bay|port|beach|ferry)$/i;

const ALWAYS_HERO = new Set([
  "hero-home",
  "og-default",
  "compare",
  "cruise-port",
  "photography",
  "highlights",
  "portofino",
  "riviera-coast",
]);

async function ensureDir(dir) {
  await fs.mkdir(dir, { recursive: true });
}

async function discoverBases() {
  const files = await fs.readdir(IMAGES_DIR);
  return files
    .filter((f) => /\.(jpe?g|png)$/i.test(f))
    .map((f) => f.replace(/\.(jpe?g|png)$/i, ""))
    .sort();
}

async function resolveInputPath(base) {
  for (const ext of [".jpg", ".jpeg", ".png"]) {
    const p = path.join(IMAGES_DIR, `${base}${ext}`);
    try {
      await fs.access(p);
      return p;
    } catch {
      /* try next */
    }
  }
  throw new Error(`missing ${base}.jpg/.png`);
}

async function inferHeroBases(bases) {
  const heroes = new Set(ALWAYS_HERO);
  for (const base of bases) {
    if (HERO_NAME_PATTERNS.test(base)) heroes.add(base);
  }
  return heroes;
}

function widthsForBase(base, sourceWidth, heroBases) {
  const pool = heroBases.has(base)
    ? [...new Set([...CARD_WIDTHS, ...HERO_WIDTHS])].sort((a, b) => a - b)
    : CARD_WIDTHS;
  return pool.filter((w) => w <= sourceWidth);
}

async function processImage(base, heroBases) {
  const inputPath = await resolveInputPath(base);
  const liveExt = path.extname(inputPath);
  const livePath = inputPath;
  const sourcePath = path.join(SOURCE_DIR, `${base}${liveExt}`);

  try {
    await fs.access(sourcePath);
  } catch {
    await fs.copyFile(livePath, sourcePath);
  }

  const meta = await sharp(sourcePath).metadata();
  const sourceWidth = meta.width ?? 1920;
  const sourceHeight = meta.height ?? 1080;
  const widths = widthsForBase(base, sourceWidth, heroBases);
  const maxWidth = Math.min(sourceWidth, heroBases.has(base) ? 1920 : 800);

  const entry = {
    base,
    width: sourceWidth,
    height: sourceHeight,
    fallbackWidth: maxWidth,
    fallbackHeight: Math.round((sourceHeight / sourceWidth) * maxWidth),
    widths,
    formats: ["avif", "webp", "jpg"],
  };

  if (base === "og-default") {
    entry.og = { width: OG_SIZE.width, height: OG_SIZE.height };
  }

  for (const w of widths) {
    const h = Math.round((sourceHeight / sourceWidth) * w);
    const pipeline = sharp(sourcePath).resize(w, h, { fit: "inside", withoutEnlargement: true });
    await pipeline.clone().avif({ quality: QUALITY.avif, effort: 4 }).toFile(path.join(OPT_DIR, `${base}-${w}w.avif`));
    await pipeline.clone().webp({ quality: QUALITY.webp }).toFile(path.join(OPT_DIR, `${base}-${w}w.webp`));
  }

  const jpgOut = path.join(IMAGES_DIR, `${base}.jpg`);
  const jpgTmp = path.join(IMAGES_DIR, `${base}.jpg.tmp`);
  await sharp(sourcePath)
    .resize(maxWidth, null, { fit: "inside", withoutEnlargement: true })
    .jpeg({ quality: QUALITY.jpeg, mozjpeg: true })
    .toFile(jpgTmp);
  await fs.rename(jpgTmp, jpgOut);

  if (base === "og-default") {
    for (const fmt of ["avif", "webp", "jpg"]) {
      const out = path.join(OPT_DIR, `${base}-og1200.${fmt}`);
      let p = sharp(sourcePath).resize(OG_SIZE.width, OG_SIZE.height, { fit: "cover", position: "centre" });
      if (fmt === "avif") p = p.avif({ quality: QUALITY.avif, effort: 4 });
      else if (fmt === "webp") p = p.webp({ quality: QUALITY.webp });
      else p = p.jpeg({ quality: QUALITY.jpeg, mozjpeg: true });
      await p.toFile(out);
    }
    entry.ogSrc = `/images/opt/og-default-og1200.jpg`;
  }

  return entry;
}

async function writeManifest(manifest) {
  const sorted = Object.fromEntries(Object.entries(manifest).sort(([a], [b]) => a.localeCompare(b)));
  const body = `/** Auto-generated by scripts/optimize-images.mjs — do not edit */\nexport const imageManifest = ${JSON.stringify(sorted, null, 2)} as const;\n\nexport type ImageManifestEntry = (typeof imageManifest)[keyof typeof imageManifest];\n`;
  await fs.writeFile(MANIFEST_TS, body);
}

async function main() {
  console.log("Optimising site images…\n");
  await ensureDir(OPT_DIR);
  await ensureDir(SOURCE_DIR);

  const bases = await discoverBases();
  if (bases.length === 0) {
    console.log("No JPG/PNG images found in public/images");
    return;
  }

  const heroBases = await inferHeroBases(bases);
  console.log(`Found ${bases.length} images (${heroBases.size} hero-sized)\n`);

  const manifest = {};
  for (const base of bases) {
    try {
      process.stdout.write(`  ${base}… `);
      manifest[base] = await processImage(base, heroBases);
      console.log("✓");
    } catch (err) {
      console.log(`✗ ${err.message}`);
    }
  }

  await writeManifest(manifest);
  console.log("\nManifest → src/data/image-manifest.ts");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
