/** Auto-generated by scripts/optimize-images.mjs — do not edit */
export const imageManifest = {
  "bay": {
    "base": "bay",
    "width": 2592,
    "height": 1944,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "beach": {
    "base": "beach",
    "width": 267,
    "height": 400,
    "fallbackWidth": 267,
    "fallbackHeight": 400,
    "widths": [],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "blue-cave": {
    "base": "blue-cave",
    "width": 4800,
    "height": 3200,
    "fallbackWidth": 800,
    "fallbackHeight": 533,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "boat": {
    "base": "boat",
    "width": 1600,
    "height": 1067,
    "fallbackWidth": 800,
    "fallbackHeight": 534,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "cable-car": {
    "base": "cable-car",
    "width": 1920,
    "height": 1280,
    "fallbackWidth": 800,
    "fallbackHeight": 533,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "city-walls": {
    "base": "city-walls",
    "width": 1920,
    "height": 1080,
    "fallbackWidth": 800,
    "fallbackHeight": 450,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "coast": {
    "base": "coast",
    "width": 1494,
    "height": 1000,
    "fallbackWidth": 800,
    "fallbackHeight": 535,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "compare": {
    "base": "compare",
    "width": 4800,
    "height": 3200,
    "fallbackWidth": 1920,
    "fallbackHeight": 1280,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "cruise-port": {
    "base": "cruise-port",
    "width": 1600,
    "height": 1200,
    "fallbackWidth": 1600,
    "fallbackHeight": 1200,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "family": {
    "base": "family",
    "width": 4227,
    "height": 2955,
    "fallbackWidth": 800,
    "fallbackHeight": 559,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "food": {
    "base": "food",
    "width": 400,
    "height": 388,
    "fallbackWidth": 400,
    "fallbackHeight": 388,
    "widths": [
      320
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "fortress": {
    "base": "fortress",
    "width": 3888,
    "height": 2592,
    "fallbackWidth": 1920,
    "fallbackHeight": 1280,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "got": {
    "base": "got",
    "width": 1251,
    "height": 1014,
    "fallbackWidth": 800,
    "fallbackHeight": 648,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "hero-home": {
    "base": "hero-home",
    "width": 3888,
    "height": 2592,
    "fallbackWidth": 1920,
    "fallbackHeight": 1280,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "highlights": {
    "base": "highlights",
    "width": 3888,
    "height": 2592,
    "fallbackWidth": 1920,
    "fallbackHeight": 1280,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "history": {
    "base": "history",
    "width": 3264,
    "height": 2448,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "lokrum": {
    "base": "lokrum",
    "width": 1600,
    "height": 777,
    "fallbackWidth": 800,
    "fallbackHeight": 389,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "luxury": {
    "base": "luxury",
    "width": 1600,
    "height": 1067,
    "fallbackWidth": 800,
    "fallbackHeight": 534,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "medieval": {
    "base": "medieval",
    "width": 3264,
    "height": 2448,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "mountains": {
    "base": "mountains",
    "width": 960,
    "height": 1280,
    "fallbackWidth": 800,
    "fallbackHeight": 1067,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "og-default": {
    "base": "og-default",
    "width": 3264,
    "height": 2448,
    "fallbackWidth": 1920,
    "fallbackHeight": 1440,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ],
    "og": {
      "width": 1200,
      "height": 630
    },
    "ogSrc": "/images/opt/og-default-og1200.jpg"
  },
  "old-town": {
    "base": "old-town",
    "width": 4573,
    "height": 3105,
    "fallbackWidth": 1920,
    "fallbackHeight": 1304,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "photography": {
    "base": "photography",
    "width": 960,
    "height": 1280,
    "fallbackWidth": 960,
    "fallbackHeight": 1280,
    "widths": [
      320,
      480,
      640,
      800,
      960
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "private": {
    "base": "private",
    "width": 4227,
    "height": 2955,
    "fallbackWidth": 800,
    "fallbackHeight": 559,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "wine": {
    "base": "wine",
    "width": 428,
    "height": 800,
    "fallbackWidth": 428,
    "fallbackHeight": 800,
    "widths": [
      320
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  }
} as const;

export type ImageManifestEntry = (typeof imageManifest)[keyof typeof imageManifest];
